import { Loader2, Sparkles } from 'lucide-react'
import { useEffect, useRef } from 'react'

import { NeedsReviewBadges } from '@/shared/components/NeedsReviewBadges'
import { useGenerateBrief, useLatestBrief } from '@/shared/hooks/useBrief'
import { formatDateTime } from '@/shared/lib/utils'
import { Button } from '@/shared/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/ui/card'

export function PrepBriefPanel({ patientId }: { patientId: string }) {
  const latestBrief = useLatestBrief(patientId)
  const generateBrief = useGenerateBrief(patientId)
  const hasAutoGeneratedRef = useRef(false)

  useEffect(() => {
    if (
      latestBrief.isSuccess &&
      latestBrief.data === null &&
      !hasAutoGeneratedRef.current &&
      !generateBrief.isPending
    ) {
      hasAutoGeneratedRef.current = true
      generateBrief.mutate()
    }
  }, [latestBrief.isSuccess, latestBrief.data, generateBrief])

  const brief = generateBrief.data ?? latestBrief.data ?? null
  const isFirstGeneration = latestBrief.data === null
  const isGenerating = generateBrief.isPending

  return (
    <Card>
      <CardHeader>
        <CardTitle>Prep brief</CardTitle>
        <CardDescription>
          Assembled from the Knowledge Profile, recent activity, and the patient's notes.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {latestBrief.isPending && (
          <p className="text-sm text-muted-foreground">Loading brief…</p>
        )}

        {latestBrief.isError && (
          <p className="text-sm text-destructive">Failed to load the brief.</p>
        )}

        {isGenerating && isFirstGeneration && (
          <p className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            Generating your first brief…
          </p>
        )}

        {!isGenerating && (brief || generateBrief.isError) && (
          <Button type="button" onClick={() => generateBrief.mutate()} disabled={isGenerating}>
            <Sparkles className="mr-1 h-4 w-4" />
            {brief ? 'Regenerate brief' : 'Generate brief'}
          </Button>
        )}

        {generateBrief.isError && (
          <p className="text-sm text-destructive">
            Failed to generate the brief. Please try again.
          </p>
        )}

        {brief && (
          <div className="space-y-4">
            <p className="text-xs text-muted-foreground">
              Generated {formatDateTime(brief.generated_at)}
            </p>
            <div>
              <p className="text-xs uppercase tracking-wide text-muted-foreground">
                Since last visit
              </p>
              <p className="mt-1 text-sm">{brief.since_last_visit}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-muted-foreground">Flags</p>
              {brief.flags.length === 0 ? (
                <p className="mt-1 text-sm text-muted-foreground">None.</p>
              ) : (
                <div className="mt-1 flex flex-wrap gap-2">
                  <NeedsReviewBadges reasons={brief.flags} />
                </div>
              )}
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-muted-foreground">
                Suggested focus
              </p>
              <p className="mt-1 text-sm">{brief.suggested_focus}</p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
